import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MusicProvider } from "./utils/music-context";
import { SidebarProvider } from "./utils/sidebar-context";
import { AudioCtxProvider } from "./utils/audio-context";
import { EntityProvider } from "./utils/entity-context";
import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "./utils/theme-context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SoneX",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 2,
  maximumScale: 2, // Optional: restricts user from zooming in
  minimumScale: 1, // Optional: restricts user from zooming out
  userScalable: false, // Optional: prevents user scaling
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

          <ThemeProvider>
            <SidebarProvider>
              <AudioCtxProvider>
                <EntityProvider>
                  <MusicProvider>{children}</MusicProvider>
                </EntityProvider>
              </AudioCtxProvider>
            </SidebarProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
