import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "./auth/Provider";
import { MusicProvider } from "./utils/music-context";
import { SidebarProvider } from "./utils/sidebar-context";
import { AudioCtxProvider } from "./utils/audio-context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SoneX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SidebarProvider>
            <AudioCtxProvider>
                <MusicProvider>{children}</MusicProvider>
            </AudioCtxProvider>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
